Dom todos
zerobasedindex/balt-public-art-mural pull request #1
Opened 2017-02-26 20:16 UTC by jjshab

All set for review

2017-02-26 20:44 UTC, zerobasedindex requested changes
Looking good man, two minor comments. Push a fix and then we can merge!

2017-02-26 20:44 UTC, zerobasedindex commented on app/src/main/java/com/gdgbaltimore/bmoreart/HomeActivity.java
> -                .findFragmentById(R.id.map);
Usually you don't static import layout resource ids. My guess the IDE did this automagically, but please change it back to `R.id.map`

2017-02-26 20:44 UTC, zerobasedindex commented on app/src/main/java/com/gdgbaltimore/bmoreart/HomeActivity.java
> +        Polyline line = googleMap.addPolyline(new PolylineOptions().add(new LatLng(39.372264, -76.711529), new LatLng(39.372264, -76.529649), new LatLng(39.207672, -76.532966),
Can you think of a better way to store these lat/lngs? It's typically bad form to inline/hard code data like this into the middle of your code. You should look at pulling this out into a member variable on the activity. (google Java class member variables).

You could use an array list to store them: http://www.anyexample.com/programming/java/java_arraylist_example.xml

Or an array: https://www.tutorialspoint.com/java/java_arrays.htm

```
private static final LatLng[] BALT_REGION = new LatLng[]{new LatLng(39.207579, -76.583704), ...};
```

In the end, the code is just being moved but it's considered to be "in a better place"

2017-02-28 03:10 UTC, jjshab commented on app/src/main/java/com/gdgbaltimore/bmoreart/HomeActivity.java
> -                .findFragmentById(R.id.map);
got it

2017-02-28 03:53 UTC, jjshab commented on app/src/main/java/com/gdgbaltimore/bmoreart/HomeActivity.java
> +        Polyline line = googleMap.addPolyline(new PolylineOptions().add(new LatLng(39.372264, -76.711529), new LatLng(39.372264, -76.529649), new LatLng(39.207672, -76.532966),
I could only come up with this, but it doesn't work. I have no idea how java variables work at all.
ArrayList<LatLng> coordlist = new ArrayList<LatLng>();

        coordlist.add(new LatLng(39.372264, -76.711529));
        coordlist.add(new LatLng(39.372264, -76.529649));
        coordlist.add(new LatLng(39.207672, -76.532966));
        coordlist.add(new LatLng(39.197325, -76.550081));
        coordlist.add(new LatLng(39.207578, -76.583704));
        coordlist.add(new LatLng(39.234661, -76.611865));
        coordlist.add(new LatLng(39.277896, -76.711035));
        coordlist.add(new LatLng(39.372264, -76.711529));



        Polyline line = map.addPolyline(new PolylineOptions()
                .add(coordlist)
                .width(5)
                .color(Color.RED));

2017-02-28 04:10 UTC, zerobasedindex commented on app/src/main/java/com/gdgbaltimore/bmoreart/HomeActivity.java
> +        Polyline line = googleMap.addPolyline(new PolylineOptions().add(new LatLng(39.372264, -76.711529), new LatLng(39.372264, -76.529649), new LatLng(39.207672, -76.532966),
You should be able to do `.add(coordlist.toArray(new LatLng[]{}))`

2017-02-28 04:17 UTC, zerobasedindex commented
@jjshab I went ahead a pushed a commit for you, please review it and let me know if you have any questions. Figured this was a good place for an example to learn from.

2017-02-28 04:17 UTC, zerobasedindex approved these changes

2017-02-28 15:57 UTC, merged